let dados = [
    {
        titulo : "Yorkshire Terrier",
        descricao : "É uma raça que conquistou o coração de muitas pessoas ao redor do mundo. Com sua aparência charmosa e personalidade marcante, o Yorkie é um excelente companheiro para diversas situações.",
        personalidade: "inteligente, alerta, alegre, brincalhão, dócil, caçador, afetuoso e teimoso.",
        porte : "pequeno",
        peso :  "2- 5kg.", 
        vida : " entre 13 e 16 anos.",
        origem: "Inglaterra",
        tags : "yorkshire terrier pequeno 3kg dócil docil afetuoso inteligente alegre brincalhao brincalhão teiomoso alerta caçador cacador",
        image: "imagens/york.jpeg",
    },
    {
        titulo: "Golden Retriever",
        descricao: "Conhecido por sua lealdade e inteligência, o Golden Retriever é um cão de família amado por muitos. É um excelente cão guia e de terapia.",
        personalidade: "Leal, inteligente, amigável, paciente, ativo.",
        porte: "Médio",
        peso: "25-34kg",
        vida: " entre 10 e 12 anos",
        origem: "Escócia",
        tags: "golden retriever Retriever amigável dourado cão de família guia terapia leal medio amigável paciente ativo",
        image: "imagens/golden.jpg"
    },
    {
        titulo: "Beagle",
        descricao: "Conhecido por seu olfato apurado e personalidade alegre, o Beagle é um cão de caça de médio porte, popular como animal de estimação. Sua natureza curiosa e amigável o torna um companheiro leal e divertido.",
        personalidade: "Alegre, amigável, curioso, independente, teimoso, caçador.",
        porte: "médio",
        peso: "10-16kg",
        vida: " entre 12 e 15 anos",
        origem: "Inglaterra",
        tags: "beagle caça olfato apurado amigável curioso teimoso médio",
        image: "imagens/beagle.jpg"
    },
    {
        titulo: "Bulldog Inglês",
        descricao: "Conhecido por sua aparência robusta e expressão fofa, o Bulldog Inglês é um cão de companhia popular. Apesar de sua aparência imponente, ele é geralmente tranquilo e amoroso.",
        personalidade: "Tranquilo, amoroso, teimoso, leal, paciente.",
        porte: "médio",
        peso: "22-25kg",
        vida: " entre 8 e 10 anos",
        origem: "Inglaterra",
        tags: "bulldog ingles forte tranquilo amoroso teimoso medio leal paciente",
        image : "imagens/bulldogingles.jpg"
    },
    {
        titulo: "Bulldog Francês",
        descricao: "O Bulldog Francês é um cão de companhia charmoso e popular, conhecido por sua aparência compacta e expressão curiosa. Apesar de seu tamanho, ele possui uma personalidade vibrante e extrovertida.",
        personalidade: "Alegre, extrovertido, brincalhão, leal, adaptável.",
        porte: "pequeno",
        peso: "8 e 14kg",
        vida: "entre 10 a 12 anos",
        origem: "França",
        tags: "bulldog frances frenchie pequeno alegre extrovertido brincalhao leal adaptável",
        image : "imagens/bulldogfrances.jpg"
    },
    {
        titulo: "Labrador Retriever",
        descricao: "Robusto e enérgico, o Labrador Retriever é um excelente cão de trabalho e companheiro. Sua versatilidade o torna popular em diversas atividades.",
        personalidade: "amigável, ativo, inteligente, leal, paciente, brincalhão e dócil.",
        porte: "médio",
        peso: "25-36 kg.",
        vida: " entre 10 e 12 anos.",
        origem: "Canadá",
        tags: "labrador retriever cachorro familia amigavel ativo medio inteligente leal paciente brincalhao docil canada",
        image: "imagens/labrador.jpg"
    },
    {
        titulo: "Husky Siberiano",
        descricao: "Conhecido por sua beleza exótica e resistência, o Husky Siberiano é um cão de trabalho originário da Sibéria. Apesar de seu tamanho, é um animal gentil e brincalhão, ideal para famílias ativas.",
        personalidade: "inteligente, independente, energético, amigável, brincalhão e vocal.",
        porte: "médio",
        peso: "16-27 kg.",
        vida: " entre 10 e 14 anos.",
        origem: "Sibéria",
        tags: "husky siberiano cachorro medio trabalho inteligente independente energetico amigavel brincalhao vocal siberia",
        image: "imagens/husky.jpg",
    },
    {
        titulo: "São Bernardo",
        descricao: "Conhecido por seu tamanho imponente e natureza gentil, o São Bernardo é um cão de montanha com um instinto protetor. Ideal para famílias com espaço e paciência.",
        personalidade: "gentil, paciente, protetor, leal, calmo e dócil.",
        porte: "gigante",
        peso: "60-90 kg.",
        vida: " entre 8 e 10 anos.",
        origem: "Suíça",
        tags: "sao bernardo gigante gentil paciente protetor leal calmo docil suiça",
        image: "imagens/saobernardo.png"
    },
    {
        titulo: "Pastor Alemão",
        descricao: "Inteligente e versátil, o Pastor Alemão é uma raça popular para trabalho e companhia. Conhecido por sua lealdade e obediência.",
        personalidade: "inteligente, leal, obediente, protetor, ativo e corajoso.",
        porte: "médio",
        peso: "30-40 kg.",
        vida: " entre 10 e 13 anos.",
        origem: "Alemanha",
        tags: "pastor alemao inteligente leal obediente medio protetor ativo corajoso alemanha",
        image: "imagens/pastoralemao.jpg"
    },
    {
        titulo: "Chihuahua",
        descricao: "O menor cão do mundo, o Chihuahua é conhecido por sua personalidade forte e corajosa. Apesar do tamanho, é um cão cheio de atitude.",
        personalidade: "corajoso, leal, alerta, teimoso, independente e afetuoso com a família.",
        porte: "muito pequeno",
        peso: "1-3 kg.",
        vida: " entre 12 e 16 anos.",
        origem: "México",
        tags: "chihuahua pequeno corajoso leal alerta teimoso independente afetuoso mexico",
        image: "imagens/chihuahua.webp",
    }, 
    {
        titulo: "Pug",
        descricao: "Charmoso e brincalhão, o Pug é um cão de companhia com uma personalidade extrovertida. Adora atenção e atividades leves.",
        personalidade: " brincalhão, sociável, afetuoso, leal, charmoso e tranquilo.",
        porte: "pequeno",
        peso: "6-8 kg.",
        vida: " entre 12 e 15 anos.",
        origem: "China",
        tags: "pug pequeno brincalhao sociavel afetuoso leal charmoso tranquilo china",
        image: "imagens/pug.png",
    },
    {
        titulo: "Shiba Inu",
        descricao: "Originário do Japão, o Shiba Inu é um cão independente e reservado com estranhos. Conhecido por sua beleza e higiene.",
        personalidade: "Independente, reservado, leal, limpo, inteligente e teimoso.",
        porte: "médio",
        peso: "7-10 kg.",
        vida: "entre 12 e 15 anos.",
        origem: "Japão",
        tags: "shiba inu japao independente reservado medio leal limpo inteligente teimoso",
        image: "imagens/shiba.webp"
    },
    {
        titulo: "Border Collie",
        descricao: "Conhecido por sua inteligência e agilidade, o Border Collie é um excelente cão de trabalho e companheiro. Necessita de muita estimulação mental e física.",
        personalidade: "inteligente, ativo, ágil, obediente, enérgico e leal.",
        porte: "médio",
        peso: "14-20 kg.",
        vida: "entre 12 e 15 anos.",
        origem: "Escócia e Inglaterra",
        tags: "border collie pastor inteligente ativo medio agil obediente energetico leal escocia inglaterra",
        image: "imagens/bodder.jpeg"
    },
    {
        titulo: "Poodle",
        descricao: "Elegante e hipoalergênico, o Poodle é um cão inteligente e versátil, disponível em três tamanhos. Ideal para apartamentos e pessoas com alergias.",
        personalidade: "Inteligente, ativo, leal, sociável, elegante e adaptável.",
        porte: "Pequeno, médio e grande",
        peso: "Varia de acordo com o tamanho",
        vida: " entre 12 e 15 anos.",
        origem: "França",
        tags: "poodle inteligente ativo leal sociavel elegante adaptable franca hipoalergenico",
        image: "imagens/poodle.jpeg"
    },
    {
        titulo: "Shih Tzu",
        descricao: "Pequeno e charmoso, o Shih Tzu é um cão de companhia com uma personalidade alegre e afetuosa. Ideal para apartamentos e pessoas que buscam um companheiro leal.",
        personalidade: "Afetuoso, brincalhão, leal, sociável, calmo e adaptável.",
        porte: "Pequeno",
        peso: "4-7 kg.",
        vida: "entre 10 e 16 anos.",
        origem: "Tibet",
        tags: "shih tzu pequeno charmoso afetuoso brincalhao leal sociavel calmo",
        image: "imagens/shihtzu.webp"
    }, 
    {
        titulo: "Akita Inu",
        descricao: "Originário do Japão, o Akita Inu é um cão leal e independente, conhecido por sua beleza e força. Requer um dono experiente.",
        personalidade: "Leal, independente, protetor, reservado com estranhos e digno.",
        porte: "Médio",
        peso: "27-34 kg.",
        vida: " entre 10 e 12 anos.",
        origem: "Japão",
        tags: "akita inu japao leal independente protetor medio reservado digno",
        image: "imagens/akitainu.jpeg"
    },
    {
        titulo: "Dachshund",
        descricao: "Popularmente conhecido como salsicha, o Dachshund é um cão com pernas curtas e corpo alongado, ideal para caça em tocas.",
        personalidade: "Curioso, corajoso, teimoso, leal e adaptável.",
        porte: "Pequeno",
        peso: "3-9 kg.",
        vida: " entre 12 e 16 anos.",
        origem: "Alemanha",
        tags: "dachshund salsicha curioso corajoso teimoso leal pequeno adaptable alemanha",
        image: "imagens/salsicha.jpeg"
    },
    {
        titulo: "Schnauzer",
        descricao: "O Schnauzer é uma raça que pode ser encontrada em três tamanhos (miniatura, padrão e gigante) e é conhecida por sua pelagem distinta e personalidade vivaz. São cães inteligentes e protetores.",
        personalidade: "inteligente, protetor, enérgico, leal, afetuoso e alerto.",
        porte: "pequeno a grande",
        peso: "5-45kg (dependendo do tamanho).",
        vida: " entre 12 e 15 anos.",
        origem: "Alemanha",
        tags: "schnauzer inteligente protetor enérgico leal afetuoso alerta",
        image: "imagens/Schnauzer.jpeg"
    },
    { 
    titulo: "Bull Terrier",
    descricao: "O Bull Terrier é conhecido por seu formato de cabeça distintivo e personalidade brincalhona. São cães muito leais e enérgicos, com uma aparência robusta.",
    personalidade: "brincalhão, leal, enérgico, inteligente, corajoso e afetuoso.",
    porte: "médio",
    peso: "20-35kg.",
    vida: " entre 10 e 14 anos.",
    origem: "Inglaterra",
    tags: "bull terrier brincalhão leal enérgico inteligente corajoso afetuoso médio",
    image: "imagens/bullterrier.jpeg"
},
{
    titulo: "Cocker Spaniel",
    descricao: "O Cocker Spaniel é uma raça popular conhecida por sua natureza afetuosa e pelagem abundante. São excelentes cães de companhia e têm uma personalidade amigável.",
    personalidade: "afetuoso, alegre, inteligente, leal, enérgico e sociável.",
    porte: "médio",
    peso: " 12-15kg.",
    vida: " entre 12 e 15 anos.",
    origem: "Inglaterra",
    tags: "cocker spaniel afetuoso alegre inteligente leal enérgico sociável médio",
    image: "imagens/cocker.jpeg"
},
{
    titulo: "Boiadeiro Australiano",
    descricao: "O Boiadeiro Austaliano é uma raça robusta e enérgica, criada para trabalhar com gado. São conhecidos por sua inteligência, lealdade e habilidades de pastoreio excepcionais.",
    personalidade: "inteligente, leal, enérgico, trabalhador, alerta e corajoso.",
    porte: "médio",
    peso: "15-25kg.",
    vida: " entre 12 e 15 anos.",
    origem: "Austrália",
    tags: "australian cattle dog inteligente boiadeiro australiano leal enérgico trabalhador alerta corajoso médio",
    image: "imagens/boiadeiro.jpeg"
},
{
    titulo: "Malamute do Alaska",
    descricao: "O Malamute do Alaska é uma raça poderosa e resistente, criada para puxar trenós e suportar climas extremos. São cães muito leais e independentes, com uma grande necessidade de exercício.",
    personalidade: "leal, enérgico, independente, inteligente, afetuoso e resistente.",
    porte: "grande",
    peso: "34-39kg.",
    vida: " entre 10 e 14 anos.",
    origem: "Alasca",
    tags: "Malamute do Alaska leal enérgico independente inteligente afetuoso resistente grande",
    image: "imagens/malamute.jpeg"
},
{
    titulo: "Lhasa Apso",
    descricao: "O Lhasa Apso é uma raça pequena com uma pelagem longa e bonita. Originário do Tibete, são conhecidos por sua natureza leal e alerta, e fazem excelentes cães de companhia.",
    personalidade: "leal, alerta, afetuoso, independente, curioso e brincalhão.",
    porte: "pequeno",
    peso: "5-8kg.",
    vida: "entre 12 e 15 anos.",
    origem: "Tibete",
    tags: "lhasa apso leal alerta afetuoso independente curioso brincalhão pequeno",
    image: "imagens/lhasa.webp",
},
{
    titulo: "Boxer",
    descricao: "O Boxer é uma raça enérgica e brincalhona, conhecida por sua natureza leal e protetora. Eles são ótimos com crianças e têm uma grande necessidade de exercícios e estimulação.",
    personalidade: "enérgico, leal, brincalhão, protetor, inteligente e afetuoso.",
    porte: "médio a grande",
    peso: "25-32kg.",
    vida: " entre 10 e 12 anos.",
    origem: "Alemanha",
    tags: "Boxer enérgico leal brincalhão protetor inteligente afetuoso médio grande",
    image: "imagens/boxer.jpeg"
},
{
    titulo: "Rottweiler",
    descricao: "O Rottweiler é uma raça robusta e poderosa, conhecida por sua lealdade e capacidade de proteção. Eles são cães muito inteligentes e confiáveis, ideais para famílias que buscam um guardião dedicado.",
    personalidade: "leal, protetor, inteligente, corajoso, enérgico e afetuoso.",
    porte: "grande",
    peso: "35-60kg.",
    vida: "entre 8 e 11 anos.",
    origem: "Alemanha",
    tags: "Rottweiler leal protetor inteligente corajoso enérgico afetuoso grande",
    image: "imagens/rot.jpeg"
},
{
    titulo: "Basenji",
    descricao: "O Basenji é uma raça pequena e elegante, conhecida por sua natureza independente e sua habilidade de caçar. Eles são conhecidos como o 'cão que não late', devido ao seu som característico.",
    personalidade: "independente, inteligente, enérgico, curioso, leal e reservado.",
    porte: "pequeno a médio",
    peso: "9-11kg.",
    vida: " entre 12 e 16 anos.",
    origem:"Congo",
    tags: "Basenji independente inteligente enérgico curioso leal reservado pequeno médio",
    image: "imagens/basenji.jpeg"
},
{
    titulo: "Terra-Nova",
    descricao: "O Terra-Nova é uma raça gigante e robusta, conhecida por sua habilidade em resgate aquático e natureza gentil. Eles são cães leais e protetores, ideais para famílias com espaço.",
    personalidade: " gentil, leal, protetor, calmo, afetuoso e inteligente.",
    porte: "gigante",
    peso: "45-68kg.",
    vida: "entre 9 e 12 anos.",
    origem: "Canadá",
    tags: "Terra Nova gentil leal protetor calmo afetuoso inteligente gigante",
    image: "imagens/terranova.jpeg"
},
{
    titulo: "Havanese",
    descricao: "O Havanese é uma raça pequena e encantadora, conhecida por sua pelagem longa e personalidade amigável. Eles são ótimos cães de companhia e se adaptam bem a diferentes ambientes.",
    personalidade: " amigável, afetuoso, inteligente, brincalhão, sociável e leal.",
    porte: "pequeno",
    peso: "4-7kg.",
    vida: "entre 14 e 16 anos.",
    origem: "Cuba",
    tags: "Havanese amigável afetuoso inteligente brincalhão sociável leal pequeno",
    image: "imagens/havanese.jpeg"
},
{
    titulo: "Welsh Corgi",
    descricao: "O Welsh Corgi é uma raça pequena e robusta, conhecida por seu corpo alongado e patas curtas. Eles são cães enérgicos e inteligentes, com uma personalidade amigável e leal.",
    personalidade: "Enérgico, inteligente, leal, amigável, curioso e afetuoso.",
    porte: "pequeno",
    peso: "10-14kg.",
    vida: " entre 12 e 15 anos.",
    origem: "País de Gales",
    tags: "Welsh Corgi enérgico inteligente leal amigável curioso afetuoso pequeno",
    image: "imagens/corgi.jpeg"
},
{
    titulo: "Briard",
    descricao: "O Briard é uma raça de pastoreio francesa conhecida por sua pelagem longa e habilidades impressionantes em trabalho com rebanhos. Eles são leais, protetores e muito inteligentes.",
    personalidade: "Leal, protetor, inteligente, enérgico, afetuoso e dedicado.",
    porte: "grande",
    peso: "30-45kg.",
    vida: " entre 10 e 12 anos.",
    origem: "França",
    tags: "Briard leal protetor inteligente enérgico afetuoso dedicado grande",
    image: "imagens/briard.jpeg"
},
{
    titulo: "Basset Hound",
    descricao: "O Basset Hound é uma raça com um olfato excepcional e uma aparência única, com orelhas longas e corpo baixo. Eles são cães afetuosos e tranquilos, conhecidos por sua natureza amigável.",
    personalidade: "Afetuoso, calmo, leal, amigável, curioso e inteligente.",
    porte: "médio",
    peso: "20-29kg.",
    vida: " entre 10 e 12 anos.",
    origem: "França",
    tags: "Basset Hound afetuoso calmo leal amigável curioso inteligente médio",
    image: "imagens/basset.jpeg"
},
{
    titulo: "Fox Paulistinha",
    descricao: "O Fox Paulistinha é uma raça pequena e ágil, conhecida por sua vivacidade e inteligência. Originário do Brasil, ele é popular por sua personalidade amigável e energia contagiante, tornando-se um excelente cão de companhia e de alerta.",
    personalidade: "Vivaz, inteligente, leal, alerta, enérgico e afetuoso.",
    porte: "pequeno",
    peso: "5-10kg.",
    vida: "entre 12 e 15 anos.",
    origem: "Brasil",
    tags: "Fox Paulistinha vivaz inteligente leal alerta enérgico afetuoso pequeno",
    image: "imagens/fox.jpeg"
},
{
    titulo: "Pinscher",
    descricao: "O Pinscher, também conhecido como Miniature Pinscher, é uma raça pequena e enérgica com uma personalidade marcante. Apesar de seu tamanho compacto, eles são conhecidos por sua coragem e vivacidade, além de serem ótimos cães de companhia.",
    personalidade: "Corajoso, enérgico, inteligente, leal, curioso e afetuoso.",
    porte: "pequeno",
    peso: "4-6kg.",
    vida: "entre 12 e 15 anos.",
    origem: "Alemanha",
    tags: "Pinscher corajoso enérgico inteligente leal curioso afetuoso pequeno",
    image:"imagens/pinscher.jpeg"
},
{
    titulo: "Fila Brasileiro",
    descricao: "O Fila Brasileiro é uma raça imponente e protetora, conhecida por sua lealdade e habilidades de guarda. Eles têm uma aparência robusta e são famosos por sua coragem e força.",
    personalidade: "Leal, protetor, corajoso, inteligente, afetuoso e reservado.",
    porte: "grande",
    peso: "40-65kg.",
    vida: " entre 9 e 11 anos.",
    origem: "Brasil",
    tags: "Fila Brasileiro leal protetor corajoso inteligente afetuoso reservado grande",
    image: "imagens/fila.jpeg"
},
{
    titulo: "Dogue Argentino",
    descricao: "O Dogue Argentino é uma raça grande e poderosa, desenvolvida para caça maior. Eles são conhecidos por sua coragem e lealdade, sendo excelentes cães de guarda e de companhia.",
    personalidade: "Corajoso, leal, protetor, inteligente, afetuoso e determinado.",
    porte: "grande",
    peso: "40-65kg.",
    vida: " entre 10 e 12 anos.",
    origem: "Argentina",
    tags: "Dogue Argentino corajoso leal protetor inteligente afetuoso determinado grande",
    image: "imagens/dogargentino.jpeg"
},
{
    titulo: "Cão de Pastor de Bergamasco",
    descricao: "O Cão de Pastor de Bergamasco é uma raça italiana conhecida por sua pelagem única e habilidades excepcionais de pastoreio. Eles são cães leais e resistentes, com um instinto natural para proteger e guiar rebanhos.",
    personalidade: "Leal, inteligente, trabalhador, protetor, afetuoso e resistente.",
    porte: "médio",
    peso: "30-43kg.",
    vida: " entre 12 e 15 anos.",
    origem: "Itália",
    tags: "Cão de Pastor de Bergamasco leal inteligente trabalhador protetor afetuoso resistente médio",
    image: "imagens/pastorbergamasco.jpeg"
},
{
    titulo: "Cão de Montanha dos Pireneus",
    descricao: "O Cão de Montanha dos Pireneus é uma raça grande e imponente, conhecida por sua pelagem espessa e habilidades de proteção. Eles são excelentes cães de guarda e pastoreio, com um temperamento gentil e protetor.",
    personalidade: "Protetor, leal, inteligente, calmo, afetuoso e corajoso.",
    porte: "grande",
    peso: "40-54kg.",
    vida: " entre 10 e 12 anos.",
    origem: "França/Espanha",
    tags: "Cão de Montanha dos Pireneus protetor leal inteligente calmo afetuoso corajoso grande",
    image: "imagens/caodamontanha.jpeg"
},
{
    titulo: "Dobermann",
    descricao: "O Dobermann é uma raça de médio a grande porte, conhecida por sua elegância, força e inteligência. Originalmente criado como cão de guarda, o Dobermann é um companheiro leal e protetor, mas exige um adestramento firme e consistente.",
    personalidade: "Inteligente, leal, corajoso, vigilante, reservado com estranhos, mas afetuoso com a família.",
    porte: "médio a grande",
    peso: "27-45kg.",
    vida: " entre 10 e 13 anos.",
    origem: "Alemanha",
    tags: "Dobermann inteligente leal corajoso vigilante reservado afetuoso grande",
    image: "imagens/doberman.jpeg"
},
{
    titulo: "Pitbull",
    descricao: "O Pitbull, ou American Staffordshire Terrier, é uma raça conhecida por sua força, energia e lealdade. Apesar dos estereótipos, são cães inteligentes, versáteis e amorosos quando socializados e treinados adequadamente.",
    personalidade: "Energético, leal, corajoso, amoroso com a família, inteligente e atlético.",
    porte: "médio",
    peso: "16-30kg.",
    vida: " entre 12 e 16 anos.",
    origem: "Estados Unidos",
    tags: "Pitbull energético leal corajoso amoroso inteligente atlético medio",
    image: "imagens/pitbull.jpeg"
},
{
    titulo: "American Bully",
    descricao: "O American Bully é uma raça relativamente nova, conhecida por sua musculatura impressionante e temperamento amável. Apesar de sua aparência forte, são cães leais, pacientes e excelentes companheiros para famílias.",
    personalidade: "Leal, paciente, amigável, confiante, brincalhão e protetor.",
    porte: "médio a grande",
    peso: "20-35kg.",
    vida: " entre 10 e 12 anos.",
    origem: "Estados Unidos",
    tags: "American Bully leal paciente amigável confiante brincalhão protetor musculoso grande",
    image: "imagens/americanbully.jpeg"
},
];
